Classiq/classiq-library

.gitignore
Using:
https://github.com/github/gitignore/blob/main/Python.gitignore
=> Add default gitignore

tutorials/phase_kickback/phase_kickback.ipynb
Change the Latex use of \ket{-} to |-\rangle in the phase kickback tutorial #38
=> Update markdown phase_kickback.ipynb by issue #38

community/QClass_2024/Submissions/HW3/Mohammadreza_Khodajou_Masouleh_HW3_QClass2024.ipynb
=> An attempt to submit HW_3

community/QClass_2024/Submissions/HW1/Rajana_Rama_Satya_Sai_Durga_Prasad_HW1_QClass2024.ipynb, community/QClass_2024/Submissions/HW2/Rajana_Rama_Satya_Sai_Durga_Prasad_HW2_QClass2024.ipynb
Submitted both HW1 and HW2 of Qclass 2024 - Classiq assignments
=> Submission of HW1 and HW2

community/QClass_2024/Submissions/HW1/Mah_Noor_HW1_QClass2024.ipynb
Hello
I am a bit behind the schedule but I really enjoyed working on this assignment.
=> Submitted the assignment, solution to HW1

community/QClass_2024/Submissions/HW1/Jose_Alejandro_Garcia_Gonzalez_HW1_QClass2024.ipynb
Resubmission of the first homework for Classiq's workshop at QClass23/24
=> Submission of HW1 for QClass23/24

community/QClass_2024/Submissions/HW2/Jose_Alejandro_Garcia_Gonzalez_HW2_QClass2024.ipynb
Resubmission of HW2 for Classiq's module at QClass23/24
=> Submission of HW2 for QClass23/24

community/QClass_2024/Submissions/HW3/José_Alejandro_García_González_HW3_VQE.ipynb
Submission of the third homework for Classiq's module at QClass23/24
=> Submission of HW3 for QClass23/24

community/QClass_2024/Submissions/HW4/Claudia_Zendejas-Morales_HW4_QClass2024.ipynb
Submission of HW4 for QClass24
by
Claudia Zendejas-Morales
=> Submission of HW4

research/rainbow_options_bruteforce_method/rainbow_options_bruteforce_method.ipynb, research/rainbow_options_bruteforce_method/rainbow_options_bruteforce_method.metadata.json, research/rainbow_options_bruteforce_method/rainbow_options_bruteforce_method.qmod, research/rainbow_options_bruteforce_method/rainbow_options_bruteforce_method.synthesis_options.json
This work completes the novel approach to price rainbow options presented in #103 with a bruteforce method introduced by Or Samimi Golan (@orsa-classiq) 
You can find all the relevant information within the research paper at [this link](https://arxiv.org/pdf/2402.05574v2)
Thanks to the other authors:
- Francesca Cibrario, 
- Or Samimi Golan, 
- Emanuele Dri, 
- Mattia Ippoliti, 
- Ron Cohen, 
- Christian Mattia, 
- Bartolomeo Montrucchio, 
- Amir Naveh, 
- Davide Corbelletto
=> Rainbow Option Pricing with bruteforce method using Classiq Platform

community/womanium/assignments/Vahid_Nourozi_hw4.ipynb
=> Womanium Final Assignment - Vahid Nourozi

community/womanium/assignments/Rishikesh_Gokhale_hw4.ipynb
=> Uploaded Classiq_Womanium_2024_final assignment

community/womanium/assignments/Mohamad_sarami_hw4.ipynb
Womanium Final Assignment - Mohamad Sarami
=> Womanium Final Assignment - Mohamad Sarami

community/womanium/assignments/Jose_Contreras_hw4.ipynb
=> Womanium Final Assignment - Jose Contreras

community/womanium/assignments/sirikarn_phuangthong_hw4.ipynb
=> Womanium Final Assignment - Sirikarn Phuangthong

community/womanium/assignments/mackenson_polché_hw4.ipynb
=> Womanium Final Assignment - Mackenson Polché

community/womanium/assignments/José_García_hw4.ipynb
=> Womanium Final Assignment - José García

community/womanium/assignments/Daniel_MontesinosCapacete_hw4.ipynb
Womanium Final Assignment - Daniel Montesinos Capacete
=> Womanium Final Assignment - Daniel Montesinos Capacete

community/womanium/assignments/Punyaporn_Onpeang_hw4.ipynb
Add file Punyaporn_Onpeang_hw4.ipynb for Assignment submission for 6.12 Advanced Algorithms Design of Punyaporn Onpeang for Womanium Quantum+AI program 2024
=> Womanium Final Assignment - Punyaporn Onpeang

community/womanium/assignments/Hitanshu_Gedam_hw4.ipynb
=> Womanium Final Assignment - Hitanshu Gedam

community/womanium/assignments/Dhawal_Verma_hw4.ipynb
=> Womanium Final Assignment - Dhawal Verma

community/womanium/assignments/Keshan_Srivastava_hw4.ipynb
=> Womanium Final Assignment - Keshan Srivastava

community/womanium/assignments/Shreya_Modi_Womanium.ipynb
Homework submission for Womanium Classiq Quantum Walks assignment
=> Womanium classiq quantum walks assignment

community/womanium/assignments/Sunil_Pattnayak_hw4.ipynb
=> Womanium Final Assignment - Sunil Pattnayak

community/womanium/assignments/Priyabrata_Bag_hw4.ipynb
The quantum walk operator for the case of a line with 16 nodes is added.
=> Womanium Final Assignment - Priyabrata Bag

Ahmet_Alperen_Tekin_hw4.ipynb
=> Womanium Final Assignment - Ahmet Alperen Tekin

community/Womanium Final Assignment - Adwaith Sajikumar
=> Womanium Final Assignment - Adwaith Sajikumar

community/womanium/assignments/Erica_Sturm_hw4.ipynb
This is Erica Sturm's first attempt at solving Womanium 2024 Module 6.12 assignment. This corresponds to the 4th homework given by Classiq.
=> Womanium Final Assignment Erica Sturm hw4

community/womanium/assignments/Prince_Dorcis_Akpaglo_hw4.ipynb
Description: Quantum walk operator for the case of a line with 16 nodes
=> Womanium Final Assignment - Prince Dorcis-Akpaglo

community/womanium/assignments/Víctor_Hernán_Torres_Brauer_hw4.ipynb
Homework for womanium and classiq certification
=> Womanium Final Assignment Víctor_Hernán_Torres_Brauer

community/womanium/assignments/Daniela_RodriguezTrujillo_hw4.ipynb.ipynb
=> Womanium Final Assignment - DANIELA RODRIGUEZ TRUJILLO

Didier_Kenigoule_hw4.ipynb
=> Womanium Final Assignment - Didier Kenigoule

community/womanium/assignments/Susana_Rivera_hw4.ipynb
first commit to library classiq
=> assigment 6.12

community/womanium/assignments/vlera_mehani_hw4.ipynb
womanium final assignment
Womanium Assignment submission
=> womanium final assignment

community/womanium/assignments/Viraj_DSouza_hw4.ipynb
Please find my updated pull request.
=> womanium-assignment4(updated request)

Attiye_moradi_hw4.ipynb
=> Womanium Final Assignment - <Attiye><Moradi>

research/README.md
=> Classiq 6.12 assignment 

community/womanium/assignments/Adriano_Lusso_hw4.ipynb
Task 6.12 of the Classiq workshop. Sorry for the late!
=> Womanium Final Assignment - Adriano Lusso

community/womanium/assignments/Şevval_Özdemir_hw4.ipynb
=> Request for Classiq Final Assignment

community/womanium/assignments/Noah_William_WQ6-12.ipynb
Assignment 6.12 submission on a different branch  (Corrected)
=> Womanium Submission 2

tests/test_notebooks.py
Should solve the problem with testing framework cannot access relative notebook files
=> A fix to the testing issue

community/womanium/assignment_4.md, community/womanium/quantum_walk_circle_example.py
=> added womanium 4th assignmenet and example code

.github/actions/run-tests/action.yml, .github/workflows/nadavs-tmp-workflow.yml
=> Refactor run tests workflow - test

.github/workflows/dev_scheduled_test.yml
=> Adding scheduled test workflow

.github/scripts/join_qmod_metadata.py, .github/workflows/deployment-qmod.yml
=> feat(deploy): add QMOD deployment flow CAD-23772

.github/actions/run-tests/action.yml
=> Adding run-tests action

CONTRIBUTING.md, README.md
fixed the issue link which was not working
This pull request addresses broken links in the repository that were preventing users from creating and viewing issues properly. The links for creating a new issue and viewing the existing ones have been updated to ensure seamless navigation for contributors and maintainers.
=> Fix: Updated Broken Links for Creating and Viewing Issues and Jozsa Algo 

.github/workflows/test-CI.yml
=> Adding test-CI.yml workflow

community/QClass_2024/Submissions/HW4/HW_4_Bill_Wisotsky.ipynb
=> docs: update HW_4_Bill_Wisotsky.ipynb

CONTRIBUTING.md, README.md
=> Reverting changes

.github/workflows/automatic-deployment.yml, .github/workflows/deployment-qmod.yml
=> feat: auto create PR for dev to main mergeing

.github/workflows/automatic-deployment.yml
=> fix(ci): auto deploy to nightly on dev merge

.github/CODEOWNERS
=> chor(ci): add codeowners to github workflows

.github/workflows/developers_onboarding_notification.yml
Closes #538 
This PR introduces a new GitHub Action that automatically posts a comment on a pull request once it has been merged into the main branch.
- [] If you're familiar with `pre-commit`, you may run `pre-commit install`, and then at each commit, your files will be altered in a similar way
=> developers onboarding action added

.github/workflows/test-ci-dev.yml
=> Updating ci

.github/workflows/test-CI.yml
=> Add GH token as env var

.github/workflows/test-CI.yml
=> Use GH context instead of GH CLI

.github/workflows/test-CI.yml
=> Set target branch as an output of the step

.github/workflows/test-CI.yml
=> Fixing bug of CI

algorithms/dqi/dqi_max_xorsat.ipynb, algorithms/dqi/dqi_max_xorsat.qmod
Small fix to decimal precision qmod of DQI
=> fix to decimal_precision dqi

.github/workflows/automatic-deployment.yml
=> Merge `pull_request_target` to dev

community/PushQuantum/final_challange_pushquantum.ipynb
=> adding pushquantum folder and ipynb

.internal/paths_for_docs.yaml, tests/resources/timeouts.yaml, tutorials/documentation_materials/classiq_101/hadamard_test/hadamard_test.ipynb, tutorials/documentation_materials/classiq_101/hadamard_test/hadamard_test.metadata.json, tutorials/documentation_materials/classiq_101/hadamard_test/hadamard_test.qmod, tutorials/documentation_materials/classiq_101/hadamard_test/hadamard_test.synthesis_options.json
=> All files of Hadamard test added

tutorials/documentation_materials/classiq_101/hadamard_test/hadamard_test.ipynb
=> Growth/adamg/cad 24013/hadamard test math fix

algorithms/dqi/dqi_max_xorsat.qmod, algorithms/dqi/dqi_max_xorsat.synthesis_options.json
=> Model/ori roth classiq/cad 25198 update dqi qmod

tutorials/technology_demonstrations/classiq_paper/qsvt/classiq_qsvt.ipynb, tutorials/technology_demonstrations/classiq_paper/qsvt/pennylane_cat_qsvt_example.ipynb, tutorials/technology_demonstrations/classiq_paper/qsvt/qiskit_qsvt.ipynb, tutorials/technology_demonstrations/classiq_paper/qsvt/tket_qsvt_example.ipynb, tutorials/technology_demonstrations/classiq_paper/quantum_walk/classiq_discrete_quantum_walk.ipynb, tutorials/technology_demonstrations/classiq_paper/quantum_walk/pennylane_catalyst_discrete_quantum_walk.ipynb, tutorials/technology_demonstrations/classiq_paper/quantum_walk/qiskit_discrete_quantum_walk.ipynb, tutorials/technology_demonstrations/classiq_paper/quantum_walk/tket_discrete_quantum_walk.ipynb
Add initial codes for generating data in the classiq paper
=> add classiq paper codes

applications/optimization/set_partition/set_partition.ipynb, tests/resources/timeouts.yaml
=> Fix failing combi notebooks

CITATION.bib
Added citation file referring to Classiq's paper
Paper Link = https://arxiv.org/abs/2412.07372
=> closes #650

algorithms/amplitude_estimation/qmc_user_defined/qmc_user_defined.ipynb
English for Introducing Quantum Functions with Quantum Monte Carlo Integration
Question: Do we really need the word "Introducing" in the title?
=> Tw Introducing Quantum Functions with Quantum Monte Carlo Integration

requirements_tests.txt
These dependencies are imported in notebooks but not defined as dependencies
=> Add dependencies that are used in existing notebooks

requirements_tests.txt
=> Add qiskit-machine-learning dependency

algorithms/algebraic/shor/shor.ipynb
English suggestions to Shor Factoring
=> English suggestions to Shor Factoring

algorithms/algebraic/shor/shor_modular_exponentiation.ipynb
English fixes to Shor's Algorithm
=> English fixes to Shor's Algorithm

.github/workflows/Test-CI-dev-daily.yml, .github/workflows/Test-CI-dev.yml, .github/workflows/Test-CI-main.yml, tests/resources/.gitattributes, tests/resources/couenne.gz, tutorials/popular_usage_examples/mcx/mcx.ipynb, tutorials/popular_usage_examples/mcx/mcx_14_ctrl_hardware.synthesis_options.json
Add `couenne` zip file to repo and install it in CI workflows
=> Install couenne in CI

tests/test_links.py
=> adding link to SKIPPED_URLS for QInnovision PR

tests/resources/timeouts.yaml, tutorials/workshops/combinatorial_workshop/combinatorial_qmod_workshop_for_maxcut.ipynb
Add qmod workshop for maxcut using the phase function
=> Basic combi workshop maxcut using phase function

tutorials/advanced_tutorials/discrete_quantum_walk/discrete_quantum_walk.ipynb
Discrete Quantum Walks suggested English changes and fixing multiple bullet lists
=> Discrete Quantum Walks suggested English changes

tests/resources/timeouts.yaml
Due to issues related to our internal testing, we increase the timeout for simple ipynb demos
=> Increase timeout for problematic demos

algorithms/differential_equations/hhl_lanchester/hhl_lanchester.ipynb, algorithms/qpe/qpe_for_matrix/qpe_for_matrix.ipynb, applications/chemistry/qpe_for_molecules/qpe_for_molecules.ipynb, tests/test_links.py
- Update test_link
- Fix broken links
=> clean test links

tutorials/advanced_tutorials/linear_combination_of_unitaries/linear_combination_of_unitaries.ipynb, tutorials/advanced_tutorials/linear_combination_of_unitaries/linear_combination_of_unitaries.qmod, tutorials/advanced_tutorials/linear_combination_of_unitaries/linear_combination_of_unitaries.synthesis_options.json
=> updating qmod file for LCU

tests/resources/timeouts.yaml
=> Increase shor_modular_exponentiation.ipynb timeout

algorithms/amplitude_estimation/quantum_counting/quantum_counting.ipynb
Quantum counting English fixes
=> Quantum counting English fixes

algorithms/qml/hybrid_qnn/hybrid_qnn_for_subset_majority.ipynb
English suggestions for hybrid QNN
=> English suggestions for hybrid QNN

algorithms/qml/qgan/qgan_bars_and_strips.ipynb
=> English suggestions for QGANs

algorithms/qml/quantum_autoencoder/quantum_autoencoder.ipynb
English suggestions for autoencoder
=> English suggestions for autoencoder

algorithms/qsvt/qsvt_fixed_point_amplitude_amplification/qsvt_fixed_point_amplitude_amplification.ipynb
English fixes to QSVT for fixed-point amplitude amplification
=> English fixes to QSVT for fixed-point amplitude amplification

algorithms/qsvt/qsvt_matrix_inversion/qsvt_matrix_inversion.ipynb
English suggestions for Using QSVT for matrix inversion
=> English suggestions for Using QSVT for matrix inversion

tutorials/popular_usage_examples/hamiltonian_simulation/hamiltonian_simulation_with_block_encoding/hamiltonian_simulation_with_block_encoding.ipynb
Hamiltonian Simulation with Block-Encoding English suggestions
=> Hamiltonian Simulation with Block-Encoding English suggestions

tutorials/documentation_materials/classiq_101/phase_kickback/phase_kickback.ipynb, tutorials/documentation_materials/classiq_101/phase_kickback/phase_kickback.synthesis_options.json
=> New visualization and minor changes to PK notebook

algorithms/differential_equations/time_marching/time_marching.ipynb
Time-Marching English suggestions
=> Time-Marching English suggestions

algorithms/qml/qgan/qgan_bars_and_strips.ipynb
=> Remove negative subscript

research/rainbow_options/rainbow_options_bruteforce_method.ipynb, research/rainbow_options/rainbow_options_bruteforce_method.qmod, research/rainbow_options/rainbow_options_bruteforce_method.synthesis_options.json, research/rainbow_options/rainbow_options_integration_method.ipynb, research/rainbow_options/rainbow_options_integration_method.qmod, research/rainbow_options/rainbow_options_integration_method.synthesis_options.json, tests/notebooks/test_rainbow_options_bruteforce_method.py, tests/notebooks/test_rainbow_options_integration_method.py
- Add test: rainbow_options_bruteforce_method
- Add test: rainbow_options_integration_method
=> more notebook tests 3

.github/workflows/Internal-automatic-deployment.yml
=> Restore Qmod deployment to staging

.github/workflows/Utils-deployment-qmod.yml
=> Deploy to staging from `main`

algorithms/algebraic/shor/shor_modular_exponentiation.ipynb
=> revering Anne changes without eliminating Nadavs updates

applications/cybersecurity/link_monitoring/link_monitoring.ipynb, applications/cybersecurity/link_monitoring/link_monitoring.synthesis_options.json, applications/cybersecurity/patching_management/patching_managment.ipynb, applications/cybersecurity/whitebox_fuzzing/whitebox_fuzzing.ipynb, tests/notebooks/test_link_monitoring.py, tests/notebooks/test_patching_managment.py, tests/notebooks/test_whitebox_fuzzing.py
- Add test: link_monitoring
- Add test: patching_managment
- Add test: whitebox_fuzzing
=> more notebook tests applications cybersecurity

tests/notebooks/test_electric_grid_optimization.py, tests/notebooks/test_integer_linear_programming.py, tests/notebooks/test_ising_model.py, tests/notebooks/test_max_clique.py, tests/notebooks/test_max_cut.py, tests/notebooks/test_max_independent_set.py, tests/notebooks/test_max_induced_k_color_subgraph.py, tests/notebooks/test_max_k_vertex_cover.py, tests/notebooks/test_min_graph_coloring.py, tests/notebooks/test_minimum_dominating_set.py, tests/notebooks/test_rectangles_packing.py, tests/notebooks/test_set_cover.py, tests/notebooks/test_set_partition.py
- Add test: electric_grid_optimization
- Add test: integer_linear_programming
- Add test: max_clique
- Add test: max_cut
- Add test: set_partition
- Add test: min_graph_coloring
- Add test: max_induced_k_color_subgraph
- Add test: max_k_vertex_cover
- Add test: max_independent_set
- Add test: minimum_dominating_set
- Add test: rectangles_packing
- Add test: set_cover
- Add test: ising_model
=> more notebook tests applications optimization

algorithms/qml/qsvm_pauli_feature_map/qsvm_pauli_feature_map.qmod, applications/finance/credit_card_fraud/credit_card_fraud.qmod
=> Update Qmod files

.github/workflows/Test-CI-main.yml
=> Update changed-files action

algorithms/algebraic/shor/shor_modular_exponentiation.ipynb
Fixed issues with headings.
The bottom part of the page doesn't seem to be rendered correctly.
=> Fixed issues with headings.

algorithms/aqc/solving_qlsp/solving_qlsp_with_aqc.ipynb
QLSP with AQC suggested English changes
=> QLSP with AQC suggested English changes

.internal/paths_for_docs.yaml
=> updated path_for_docs to include new paths of hadamard, kickback and lcu

tutorials/classiq_101/classiq_concepts/design/classical_variables_and_operations/classical_variables_and_operations.ipynb, tutorials/classiq_101/quantum_primitives/linear_combination_of_unitaries/linear_combination_of_unitaries.ipynb
=> Changed names of LCU and Design - classical control flow

algorithms/swap_test/swap_test.ipynb
=> Swap test English suggestions

tutorials/basic_tutorials/mcx/mcx.ipynb
MCX tutorial English suggestions
=> MCX tutorial English suggestions

algorithms/qml/qsvm_pauli_feature_map/qsvm_pauli_feature_map.ipynb
Qsvm pauli feature map English suggestions
I can't see how to fix the page title. Instead of Qsvm pauli feature map it should be QSVM Pauli Feature Map.
=> Qsvm Pauli Feature Map English suggestions

algorithms/qml/quantum_autoencoder/quantum_autoencoder.ipynb
Quantum Autoencoder more English suggestions
=> Quantum Autoencoder more English suggestions

community/paper_implementation_project/index.md
=> adding papaer implementation project folder

CONTRIBUTING.md, community/paper_implementation_project/index.md
=> Update contribution instructions 

algorithms/glued_trees/glued_trees.ipynb
Glued Trees English suggestions
=> Glued Trees English suggestions

algorithms/qml/qsvm/qsvm.ipynb
QSVM minor corrections
Note that the fourth bullet (before "Coding QSVM") does not render correctly. It looks fine in Jupyter Lab, but appears as #1 in the browser. I don't know how to fix this.
=> QSVM minor corrections

tests/utils_for_testbook.py
=> Fix loading of synthesis results into a QuantumProgram

applications/benchmarking/quantum_volume/quantum_volume.ipynb
Quantum volume English suggestions, fixing references
=> Quantum volume English suggestions

requirements_tests.txt
Since the original issue with osqp was fixed
=> Revert "Pin osqp version"

applications/chemistry/molecule_eigensolver/molecule_eigensolver.ipynb
Chemistry Molecule Eigensolver English suggestions
=> Chemistry Molecule Eigensolver English suggestions

applications/chemistry/molecule_eigensolver_using_openfermion/molecule_eigensolver_using_openfermion.ipynb
This PR fixes an issue with the path for testing
=> work with pathlib

algorithms/deutsch_jozsa/deutsch_jozsa.ipynb
=> updating images in notebook

community/Hackathons/iQuHack_2025/Challenge_solution/winning_solution/classiq_iQuHack_2025_quantum_tree_sol.ipynb
=> Fix writing of qprog

algorithms/differential_equations/hhl_lanchester/hhl_lanchester.qmod
=> Remove trailing comma in HHL Lanchester model array

tests/utils_for_testbook.py
- Add a decorator to help `test_notebook` represent which notebook it's testing
- Add comments about the decorators
=> add testbook repr

.github/pull_request_template.md, .internal/pre_commit_tools/clean_timeouts.py, .internal/pre_commit_tools/notebook_pre_commit_collection.py, .internal/pre_commit_tools/qmod_pre_commit_collection.py, CONTRIBUTING.md, README.md
- Update pre-commit messages
- Update pull-request template to note about pre-commit
- Enable pre-commit CI
- Add `pre-commit` to `requirements.txt`
- Add `pre-commit` to CONTRIBUTING.md
- Add documentation to install via requirements.txt (which installs classiq, jupyter, and pre-commit)
=> improve pre commit message

algorithms/qaoa/maxcut/qaoa_maxcut.metadata.json
Reverts Classiq/classiq-library#971
=> Revert "Add files via upload"

algorithms/algebraic/shor/doubly_controlled_modular_adder.qmod, algorithms/algebraic/shor/doubly_controlled_modular_adder.synthesis_options.json, algorithms/algebraic/shor/shor.qmod, algorithms/algebraic/shor/shor.synthesis_options.json
=> Update Shor Qmod files

algorithms/oblivious_amplitude_amplification/oblivious_amplitude_amplification.ipynb
Closes Issue #919
Oblivious Amplitude Amplification: Fixing a few typos
=> Oblivious Amplitude Amplification: Fixing a few typos

applications/chemistry/protein_folding/protein_folding.ipynb
New PR: Chemistry Protein folding English suggestions
=> New PR: Chemistry Protein folding English suggestions

tests/notebooks/test_3sat_oracles.py, tests/notebooks/workshops/test_hadamard_test.py, tutorials/classiq_101/quantum_primitives/hadamard_test/hadamard_test.ipynb, tutorials/technology_demonstrations/classiq_paper/quantum_walk/classiq_discrete_quantum_walk.ipynb
=> Fix some notebooks

.github/workflows/Test-CI-main.yml, tests/test_links.py, tests/utils_for_tests.py
- Send changed test files to the tests
- delete me
=> run notebooks tests based on changed tests

algorithms/bernstein_vazirani/bernstein_vazirani.ipynb
=> Fixed figure numbering

tests/resources/timeouts.yaml
Increase demo timeouts following changes in #1000
=> Increase demo timeouts

algorithms/dqi/dqi_max_xorsat.ipynb
=> Fix DQI model errors

applications/chemistry/qpe_for_molecules/qpe_for_molecules.ipynb
English suggestions for QPE for molecules
=> English suggestions for QPE for molecules

applications/cybersecurity/link_monitoring/link_monitoring.ipynb
English suggestions for cyber link monitoring
=> English suggestions for cyber link monitoring

applications/cybersecurity/patching_management/patch_min_vertex_cover.ipynb
English suggestions for patch management kill chains
=> English suggestions for patch management kill chains

.internal/paths_for_docs.yaml
Following #1067 the auto-generated name was changed
=> Fix QML with Classiq guide pic name

.internal/pre_commit_tools/auto_add_tests.py, .internal/pre_commit_tools/notebook_pre_commit_collection.py, .internal/pre_commit_tools/qmod_pre_commit_collection.py, tests/internal/test_pre_commit.py, tests/test_all_notebooks_are_tested.py
- Fix auto_add_tests old syntax
- Forbid space in file names
- Fix test name
- Improve is_valid_qmod error message
- Expand error message on notebook without test
=> improve pre commit message 2

tests/notebooks/test_execution_tutorial.py, tutorials/basic_tutorials/the_classiq_tutorial/execution_tutorial.ipynb
Execution tutorial: temporary fix for IBM Preferences.
=> Removing Hardware Execution from Execution Tutorial

README.md
Add link to AI documentation in the readme
=> add ai to readme

tutorials/basic_tutorials/the_classiq_tutorial/execution_tutorial.ipynb, tutorials/basic_tutorials/the_classiq_tutorial/execution_tutorial_part2.ipynb
=> Modifying the titles of the exec tutorials to keep the standard

applications/finance/option_pricing/option_pricing.ipynb
English suggestions for Estimating European Option Price
=> English suggestions for Estimating European Option Price

algorithms/algebraic/shor/shor.ipynb
=> Remove duplicate image

applications/logistics/task_scheduling_problem/task_scheduling_problem.ipynb
English suggestions for Workflow Scheduling
=> English suggestions for Workflow Scheduling

README.md
The IDE code in the README.md did not synthesize. This change will make sure you can synthesize it.
=> Make sure the readme code works

tutorials/workshops/algo_design_QCE_tutorial/algo_design_QCE_tutorial_part_I.ipynb
Add boilerplate code to all examples
=> Add boilerplate code to exercises

.github/workflows/Test-CI-daily-internal.yml, .github/workflows/Test-CI-daily-notebooks-algorithms.yml, .github/workflows/Test-CI-daily-notebooks-applications.yml, .github/workflows/Test-CI-daily-notebooks-other.yml, .github/workflows/Test-CI-daily-notebooks-tutorials.yml, tests/utils_for_testbook.py
=> Model/ori roth classiq/add qmod comparison tests

applications/automotive/cooling_systems_optimization/cooling_systems_optimization.ipynb
=> Remove QArray iteration

applications/optimization/kidney_exchange/kidney_exchange_problem.ipynb
English suggestions for kidney exchange
=> English suggestions for kidney exchange

applications/optimization/electric_grid_optimization/electric_grid_optimization.ipynb
English suggestions for Electric Grid
=> English suggestions for Electric Grid

applications/logistics/vehicle_routing_problem/vehicle_routing_problem.ipynb
English suggestions to Vehicle Routing
=> English suggestions to Vehicle Routing

applications/finance/autocallable_options/partial_exponential_state_preparation.ipynb, applications/finance/autocallable_options/quantum_autocallable_option_pricing.ipynb
Minor English fixes to autocallable notebooks
=> Minor English fixes to autocallable notebooks

.github/actions/send_qmods_slack_notification/action.yml, .github/workflows/Test-CI-daily-internal.yml, .github/workflows/Test-CI-daily-notebooks-algorithms.yml, .github/workflows/Test-CI-daily-notebooks-applications.yml, .github/workflows/Test-CI-daily-notebooks-other.yml, .github/workflows/Test-CI-daily-notebooks-tutorials.yml
=> Fix test output file path

algorithms/qml/hybrid_qnn/hybrid_qnn_for_subset_majority.ipynb, algorithms/qml/qgan/qgan_bars_and_strips.ipynb, algorithms/qml/qsvm/qsvm.ipynb, algorithms/qml/qsvm_pauli_feature_map/qsvm_pauli_feature_map.ipynb, algorithms/qml/quantum_autoencoder/quantum_autoencoder.ipynb, applications/finance/credit_card_fraud/credit_card_fraud.ipynb, tutorials/basic_tutorials/qml_with_classiq_guide/qml_with_classiq_guide.ipynb
This PR adds the installation of "classiq[qml]" to qml notebooks, making them standalone for users/studio
=> add classiq qml installation in notebooks
