algorithms/algebraic/discrete_log/discrete_log.ipynb
algorithms/algebraic/discrete_log/discrete_log.qmod

Updated the variable names for improved the readability and adherence

Refactoring the names of the variable for clarity and consistency in discrete_log.ipynb 

---

tutorials/classiq_concepts/design/design/design.ipynb

Fix typo in `design.ipynb`

---

community/womanium/assignments/Petra_Brcic_hw4.ipynb

Final assignment for Classiq module as part of Womanium.

Womanium Final Assignment - Petra Brčić

---

community/womanium/assignments/Karan_Islur_hw4.ipynb.ipynb

Womanium Final Assignment - Karan Y Islur

---

tutorials/getting_started/part3_deutsch_jozsa.ipynb
tutorials/getting_started/part4_ghz_state.ipynb

I have updated the getting started tutorial to use the generative functions and remove some parts of the code that where not needed.

Small changes in the getting started tutorial

---

CONTRIBUTING.md
README.md

Reverting changes

---

.github/workflows/test-ci-dev.yml

moving action to test-ci-dev

---

functions/open_library_definitions/amplitude_estimation.qmod
functions/open_library_definitions/qpe.qmod
functions/open_library_definitions/qpe_flexible.qmod

Fix Qmods that use reserved word "phase" as variable name

---

.github/workflows/test-CI.yml

Fixing bug of running all notebooks when it is not needed

---

.github/workflows/automatic-deployment.yml

When the trigger is a PR from a fork, the workflow runs in the fork, and thus has no access to the repo secrets
So we should trigger based on push rather than merged PR

Change the automatic deployment trigger from PR to push

---

.github/workflows/Test-CI-dev-daily.yml
.github/workflows/Test-CI-dev.yml
.github/workflows/Test-CI-main.yml

- Initial split of test-CI into main,dev,dev-nightly
- Update Test-CI-main
- Update test-CI-dev
- remove caching from dev test, since I'm not sure about the version name convention for dev versions
- remove unneeded env-vars from the inline script in the CI
- Update test-CI-dev-daily

split test ci workflows 2

---

tests/test_links.py

adding SKIPPED_URLS list

---

algorithms/algebraic/discrete_log/discrete_log.ipynb

English for Discrete Logarithm.

Suggested English changes to Discrete Logarithm

---

algorithms/algebraic/hidden_shift/hidden_shift.ipynb

English suggestions for hidden_shift

English suggestions for hidden_shift

---

algorithms/differential_equations/discrete_poisson_solver/discrete_poisson_solver.ipynb
tests/resources/timeouts.yaml
tests/test_links.py

Poisson equation English suggestions

Discrete Poisson solver English suggestions

---

.github/workflows/Test-CI-dev-daily.yml
.github/workflows/Test-CI-dev.yml
.github/workflows/Test-CI-main.yml

Instead of committing the executable in the repo, we obtain it from a resource bucket in S3
[Successful run](https://github.com/Classiq/classiq-library/actions/runs/12733177823) (in the CI it doesn't actually run the test because the notebook is not changed)

Install couenne solver from S3

---

algorithms/algebraic/shor/doubly_controlled_modular_adder.qmod
algorithms/algebraic/shor/doubly_controlled_modular_adder.synthesis_options.json
algorithms/algebraic/shor/shor_modular_exponentiation.ipynb
algorithms/algebraic/shor/shor_modular_exponentiation.qmod
algorithms/algebraic/shor/shor_modular_exponentiation.synthesis_options.json

Shor in library corrected - post-processing

---

tests/notebooks/test_bernstein_vazirani.py
tests/notebooks/test_hidden_shift.py
tests/utils_for_testbook.py
tests/utils_for_tests.py

- Prepare testing utils for testing specific notebooks
- Add tests for 2 notebooks (bernstein_vazirani and hidden_shift)
- delete me - only triggering tests

add tests to specific notebooks 2

---

algorithms/simon/simon.ipynb

Attempting to fix display of numbered list in Simon

Attempting to fix display of numbered list in Simon

---

.github/workflows/Test-CI-dev-daily.yml
.github/workflows/Test-CI-dev.yml
.github/workflows/Test-CI-main.yml
algorithms/dqi/dqi_max_xorsat.ipynb
tests/resources/.gitattributes
tests/resources/couenne.gz

max-XORSAT English suggestions

DQI max-XORSAT English suggestions

---

algorithms/aqc/solving_qlsp/solving_qlsp_with_aqc.ipynb
algorithms/aqc/solving_qlsp/solving_qlsp_with_aqc.synthesis_options.json

Co-authored-by: Lin Lin <linlin@math.berkeley.edu>
Co-authored-by: Dong An <dongan@pku.edu.cn>

QLSP notebook adding contributors

---

algorithms/swap_test/swap_test.ipynb
algorithms/swap_test/swap_test.synthesis_options.json
tutorials/advanced_tutorials/linear_combination_of_unitaries/linear_combination_of_unitaries.ipynb
tutorials/documentation_materials/classiq_101/hadamard_test/hadamard_test.ipynb
tutorials/documentation_materials/classiq_101/phase_kickback/phase_kickback.ipynb

Fixing small errors in 101

---

algorithms/vqls/lcu_vqls/vqls_with_lcu.ipynb

English suggestions for VQLS

---

algorithms/oblivious_amplitude_amplification/oblivious_amplitude_amplification.ipynb

English changes to Oblivious Amplitude Amplification

English changes to Oblivious Amplitude Amplification

---

algorithms/qml/qgan/qgan_bars_and_strips.ipynb

Negative subscripts are currently not supported in Qmod.

Model/ori roth classiq/fix qgans notebook

---

community/Hackathons/QInnovision_2025/advection_equation/advection.ipynb
community/Hackathons/iQuHack_2025/ Challenge_solution/our_ solution/classiq_iQuHack_2025_final_sol.ipynb
community/Hackathons/iQuHack_2025/ Challenge_solution/winning_solution/classiq_iQuHack_2025_quantum_tree_sol.ipynb
community/Hackathons/iQuHack_2025/Challenge/classiq_iQuHack_2025_final.ipynb
community/Hackathons/iQuHack_2025/Workshop/WS_iQuHack_2025_final.ipynb
tests/resources/timeouts.yaml

added quantum tree solution for mit iquhack 2025

---

algorithms/grover/grover_max_cut/grover_max_cut.ipynb

Graph Cut Search Problem with Grover Oracle English suggestions
Fixing the heading levels so they show up on the right

Graph Cut Search Problem with Grover Oracle English suggestions

---

applications/chemistry/molecular_energy_curve/molecular_energy_curve.ipynb
applications/chemistry/molecular_energy_curve/molecular_energy_curve.synthesis_options.json
applications/chemistry/molecule_eigensolver/molecule_eigensolver.ipynb
applications/chemistry/protein_folding/protein_folding.synthesis_options.json
tests/notebooks/test_molecular_energy_curve.py
tests/notebooks/test_molecule_eigensolver.py
tests/notebooks/test_protein_folding.py
tests/notebooks/test_qpe_for_molecules.py
tests/notebooks/test_second_quantized_hamiltonian.py
tests/test_no_errors.py

- Add test: molecular_energy_curve
- Add test: molecule_eigensolver
- Add test: protein_folding
- Add test: qpe_for_molecules
- Add test: second_quantized_hamiltonian

more notebook tests applications chemistry

---

applications/logistics/task_scheduling_problem/task_scheduling_problem.ipynb
tests/notebooks/test_facility_location.py
tests/notebooks/test_task_scheduling_problem.py
tests/notebooks/test_traveling_salesman_problem.py

- Add test: facility_location
- Add test: task_scheduling_problem
- Add test: traveling_salesman_problem

more notebook tests applications logistics

---

applications/finance/option_pricing/option_pricing.ipynb
tests/notebooks/test_credit_card_fraud.py
tests/notebooks/test_option_pricing.py
tests/notebooks/test_portfolio_optimization.py
tests/utils_for_testbook.py

- Add test: credit_card_fraud
- Add test: option_pricing
- Add test: portfolio_optimization

more notebook tests applications finance

---

tests/notebooks/workshops/test_Qmod_tutorial_part1.py
tests/notebooks/workshops/test_Qmod_tutorial_part2.py
tests/notebooks/workshops/test_classiq_overview_tutorial.py
tests/notebooks/workshops/test_synthesis_tutorial.py
tests/test_notebooks.py
tutorials/Classiq_tutorial/Qmod_tutorial_part1.ipynb
tutorials/Classiq_tutorial/Qmod_tutorial_part2.ipynb
tutorials/Classiq_tutorial/classiq_overview_tutorial.ipynb
tutorials/Classiq_tutorial/synthesis_tutorial.ipynb

- Add test: classiq_overview_tutorial
- Add tests: Qmod_tutorial_part1 Qmod_tutorial_part2
- Add test: synthesis_tutorial

more notebook tests tutorials classiq tutorials

---

.internal/docs_directories.txt
tests/internal/test_paths_for_docs.py

This file contains the list of directories that should be copied to our docs
Also added a test to verify that all dirs in the file exist

[Internal] create `docs_directories.txt` file

---

algorithms/qml/qsvm/qsvm.ipynb

QSVM English suggestions

---

algorithms/differential_equations/discrete_poisson_solver/discrete_poisson_solver.ipynb

Poisson solver fixing a typo

---

tests/notebooks/test_hhl_lanchester.py
tests/notebooks/test_qaoa_maxcut.py
tests/notebooks/test_rainbow_options_direct_method.py
tests/notebooks/test_rectangles_packing_grid.py
tests/notebooks/test_shor.py
tests/notebooks/test_shor_modular_exponentiation.py
tests/notebooks/test_time_marching.py
tests/test_all_notebooks_are_tested.py
tests/utils_for_tests.py

- Add test verifying that all notebooks are tested
- Create tests (WIP)

enforce testing notebooks 2

---

algorithms/dqi/dqi_max_xorsat.ipynb

The DQI notebook constructs a random graph with `seed=0`.
When NetwrokX encounters an `int` seed, it creates a Python RNG. However, Python's RNG does not guarantee to be consistent across platforms https://stackoverflow.com/questions/8786084/reproducibility-of-python-pseudo-random-numbers-across-systems-and-versions.
So instead, I set the notebook to explicitly allocate a Numpy RNG, which does provide this guarantee https://stackoverflow.com/questions/40676205/cross-platform-numpy-random-seed.
Using `np.default_rng(seed=11)` specifically ensures that the matrix B is generated the same way it was generated when the notebook was written.

Update RNG seed in DQI notebook

---

tutorials/basic_tutorials/hamiltonian_simulation/hamiltonian_simulation_with_block_encoding/hamiltonian_simulation_with_block_encoding.ipynb

- Fixed broken links in hamiltonian_simulation_with_block_encoding.ipynb
- Updated paths from classiq_101/quantum_primitives to basic_tutorials/quantum_primitives
- Resolves CI test_links failure

fix: update broken links to LCU tutorial

---

.internal/paths_for_docs.yaml
tests/internal/test_paths_for_docs.py

Use `"*.png"` as name for auto-generated images, to avoid the need of hard-coding the name

Use wildcard in auto-generated image names

---

.github/workflows/Test-CI-daily-internal.yml
.github/workflows/Test-CI-daily-notebooks-algorithms.yml
.github/workflows/Test-CI-daily-notebooks-applications.yml
.github/workflows/Test-CI-daily-notebooks-other.yml
.github/workflows/Test-CI-daily-notebooks-tutorials.yml
.github/workflows/Test-CI-main.yml

In main workflow just use default values
In weekly workflows set to `nightly.platform.classiq.io` and not directly to the API

Fix `CLASSIQ_HOST` value in workflows

---

tests/qmods/test_qmods.py

The environment variable includes the relative path, rather than just the name, so we need to filter based on that

Fix qmod fetching

---

applications/cybersecurity/whitebox_fuzzing/whitebox_fuzzing.ipynb

English fixes to whitebox fuzzing

English fixes to whitebox fuzzing

---

tutorials/basic_tutorials/the_classiq_tutorial/classiq_overview_tutorial.ipynb

Fixing a broken link in the classiq overview tutorial due to the change latest/classiq_101 to latest/getting-started.

Fixing Broken Link

---

algorithms/hamiltonian_simulation/hamiltonian_simulation_with_block_encoding/hamiltonian_simulation_with_block_encoding.ipynb
algorithms/vqls/lcu_vqls/vqls_with_lcu.ipynb
tutorials/advanced_tutorials/high_level_modeling_flexible_qpe/high_level_modeling_flexible_qpe.ipynb

Fix hamiltonian_to_matrix usages
